# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = C:\Program Files\Epic Games\UE_5.5

TARGETS = \
	LiveLinkHub-Win64-DebugGame  \
	LiveLinkHub-Win64-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	EventLoopUnitTests \
	UnrealEditor-Win64-DebugGame  \
	UnrealEditor-Win64-Development  \
	UnrealEditor \
	UnrealGame-Win64-DebugGame  \
	UnrealGame-Win64-Development  \
	UnrealGame-Win64-Shipping  \
	UnrealGame \
	TCG_Sample-Win64-DebugGame  \
	TCG_Sample-Win64-Development  \
	TCG_Sample-Win64-Shipping  \
	TCG_Sample \
	TCG_SampleEditor-Win64-DebugGame  \
	TCG_SampleEditor-Win64-Development  \
	TCG_SampleEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.bat"

all: StandardSet

RequiredTools: CrashReportClient-Win64-Shipping CrashReportClientEditor-Win64-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Win64-Shipping

StandardSet: RequiredTools UnrealFrontend TCG_SampleEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Win64-Debug TCG_SampleEditor-Win64-Debug


LiveLinkHub-Win64-DebugGame:
	 $(BUILD) LiveLinkHub Win64 DebugGame  $(ARGS)

LiveLinkHub-Win64-Development:
	 $(BUILD) LiveLinkHub Win64 Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Win64-Development

DotNetPerforceLib: DotNetPerforceLib-Win64-Development

EventLoopUnitTests: EventLoopUnitTests-Win64-Development

UnrealEditor-Win64-DebugGame:
	 $(BUILD) UnrealEditor Win64 DebugGame  $(ARGS)

UnrealEditor-Win64-Development:
	 $(BUILD) UnrealEditor Win64 Development  $(ARGS)

UnrealEditor: UnrealEditor-Win64-Development

UnrealGame-Win64-DebugGame:
	 $(BUILD) UnrealGame Win64 DebugGame  $(ARGS)

UnrealGame-Win64-Development:
	 $(BUILD) UnrealGame Win64 Development  $(ARGS)

UnrealGame-Win64-Shipping:
	 $(BUILD) UnrealGame Win64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Win64-Development

TCG_Sample-Win64-DebugGame:
	 $(BUILD) TCG_Sample Win64 DebugGame  -Project="C:\Users\PC\Documents\Fork\TCG_Sample\TCG_Sample.uproject" $(ARGS)

TCG_Sample-Win64-Development:
	 $(BUILD) TCG_Sample Win64 Development  -Project="C:\Users\PC\Documents\Fork\TCG_Sample\TCG_Sample.uproject" $(ARGS)

TCG_Sample-Win64-Shipping:
	 $(BUILD) TCG_Sample Win64 Shipping  -Project="C:\Users\PC\Documents\Fork\TCG_Sample\TCG_Sample.uproject" $(ARGS)

TCG_Sample: TCG_Sample-Win64-Development

TCG_SampleEditor-Win64-DebugGame:
	 $(BUILD) TCG_SampleEditor Win64 DebugGame  -Project="C:\Users\PC\Documents\Fork\TCG_Sample\TCG_Sample.uproject" $(ARGS)

TCG_SampleEditor-Win64-Development:
	 $(BUILD) TCG_SampleEditor Win64 Development  -Project="C:\Users\PC\Documents\Fork\TCG_Sample\TCG_Sample.uproject" $(ARGS)

TCG_SampleEditor: TCG_SampleEditor-Win64-Development

configure:
	$(BUILD) -ProjectFiles -Project="C:\Users\PC\Documents\Fork\TCG_Sample\TCG_Sample.uproject" -Game 

.PHONY: $(TARGETS)
